calculate_area_length = input("What is the length?: ")
calculate_area_width = input("What is the width ?: ")
calculate_area_length = float(calculate_area_length)
calculate_area_width = float(calculate_area_width)
print("The parameter is:")
print(calculate_area_length + calculate_area_width)
print("The area is:")
print(calculate_area_length * calculate_area_width)